export const stacksData = [
  {
    id: '1386a9fc-5e1e-4c95-85de-1fda8b581110',
    image: '/home/StrategicExecutive.jpg',
    title: 'Strategic Executive Advisory Services & Consulting',
    desc: 'We provide strategic advice and consulting to executives to help them make better decisions, convert those decisions to actions, and deliver the sustainable success they desire.',
    link: 'https://www.ondemand-innovation.com/strategic-executive-advisory-service-consulting/',
  },
  {
    id: 'd0ee62c3-b523-4fbc-befd-f0070fb6bcb0',
    image: '/home/StaffAugmentation.jpg',
    title: 'Staff Augmentation, Custom Application & Integration Development',
    desc: 'We offer staff augmentation services to help you quickly ramp up your team and meet business objectives. We also provide custom application and integration development services to help you streamline your business processes.',
    link: 'https://www.ondemand-innovation.com/staff-augmentation-custom-application-integration-development/',
  },
  {
    id: '27eb4af8-ad64-45cb-87f9-9c5b3d3bda14',
    image: '/home/CyberSecurity.jpg',
    title: 'Cyber Security Services',
    desc: 'Our cybersecurity services protect your business from cyber threats, allowing you to focus on what you do best.',
    link: 'https://www.kaspersky.com/resource-center/definitions/what-is-cyber-security',
  },
  {
    id: 'cd204222-bb33-46aa-ba9f-2b129c4559e8',
    image: '/home/FormWorkFlow.jpg',
    title: 'Forms & Workflow Automation',
    desc: 'We automate your forms and workflows, reducing manual work and increasing efficiency.',
    link: 'https://www.ondemand-innovation.com/forms-and-workflow-automation/',
  },
  {
    id: '9a01845a-ee9a-435a-892f-4ecba4897ee9',
    image: '/home/CloudService.jpg',
    title: 'Cloud Services',
    desc: 'Our cloud services help you leverage the power of cloud computing, reducing IT costs and improving scalability.',
    link: 'https://www.ondemand-innovation.com/cloud-services/',
  },
  {
    id: '0565aec4-775d-4bb7-9b2c-3f69e0e2fe1f',
    image: '/home/SystemDevelopment.jpg',
    title: 'System Development',
    desc: 'We develop systems tailored to your business needs, helping you improve operations and grow your business.',
    link: 'https://www.sciencedirect.com/topics/computer-science/system-development',
  },
  {
    id: '350691a6-b5e9-44d6-bbdb-93a4cc19ef8c',
    image: '/home/SocialMarketing.jpg',
    title: 'Social Media Marketing',
    desc: 'Our social media marketing services help you reach your target audience, increase your brand visibility and improve your ROI.',
    link: 'https://www.investopedia.com/terms/s/social-media-marketing-smm.asp',
  },
  {
    id: 'd4d89a15-f668-4f3f-a8bb-7dc2528b25e2',
    image: '/home/SoftwareIntegration.jpg',
    title: 'Software Integration',
    desc: 'We integrate your software systems, allowing them to work together seamlessly and improving your business efficiency.',
    link: 'https://www.workato.com/the-connector/software-integration/',
  },
  {
    id: 'ef52dfd1-5aaa-4233-9d95-423c3e9ff54f',
    image: '/home/GraphicDesign.jpg',
    title: 'Graphics Design',
    desc: 'Our graphics design services help you create visually appealing and effective designs for your business.',
    link: 'https://www.interaction-design.org/literature/topics/graphic-design',
  },
]
