export const data = [
  {
    id: 1,
    name: 'Jonathan Doe',
    text: 'Jonathan has been a key player in our team, consistently delivering high-quality code. His attention to detail and dedication to frontend development have greatly improved our project.',
    role: 'Frontend Developer',
    imgUrl: '/Avatar.jpg',
  },
  {
    id: 2,
    name: 'Josiah Sunday',
    text: 'Josiah is a highly skilled developer with a knack for creating intuitive user interfaces. His contributions have significantly enhanced the user experience of our product.',
    role: 'Frontend Developer',
    imgUrl: '/Avatar.jpg',
  },
  {
    id: 3,
    name: 'Rusty Amazing',
    text: 'Rusty has a comprehensive understanding of both frontend and backend development. His ability to solve complex problems and implement robust solutions has been invaluable to our team.',
    role: 'FullStack Developer',
    imgUrl: '/Avatar.jpg',
  },
  {
    id: 4,
    name: 'Gieanne Namikaze',
    text: 'Gieanne has an exceptional ability to present complex ideas in a clear and engaging manner. Her presentations have consistently received positive feedback for their clarity and effectiveness.',
    role: 'Presenter',
    imgUrl: '/Girl Avatar.jpg',
  },
  {
    id: 5,
    name: 'Ken Chan',
    text: "Ken is a talented UI/UX designer who consistently delivers intuitive and visually appealing designs. His keen eye for detail and understanding of user behavior have greatly improved our product's usability.",
    role: 'UI/UX Designer',
    imgUrl: '/Avatar.jpg',
  },
  {
    id: 6,
    name: 'John Doe',
    text: 'John is a skilled UI/UX designer with a knack for creating user-friendly interfaces. His innovative design solutions have significantly enhanced the user experience of our product.',
    role: 'UI/UX Designer',
    imgUrl: '/Avatar.jpg',
  },
  {
    id: 7,
    name: 'Jane Smith',
    text: "Jane is a creative UI/UX designer who excels at transforming complex ideas into simple, intuitive designs. Her user-centric approach has been instrumental in improving our product's usability.",
    role: 'UI/UX Designer',
    imgUrl: '/Girl Avatar.jpg',
  },
  {
    id: 8,
    name: 'Emily Johnson',
    text: 'Emily is a dedicated UI/UX designer who consistently produces high-quality designs. Her ability to understand and cater to user needs has greatly contributed to the success of our product.',
    role: 'UI/UX Designer',
    imgUrl: '/Girl Avatar.jpg',
  },
  {
    id: 9,
    name: 'Robert Brown',
    text: 'Robert is a proficient UI/UX designer whose innovative designs have consistently improved the user experience of our product. His ability to balance aesthetics and functionality in his designs is commendable.',
    role: 'UI/UX Designer',
    imgUrl: '/Avatar.jpg',
  },
].sort((a, b) => a.name.localeCompare(b.name))
